version: "3.1"

services:

  portainer:
    image: portainer/portainer
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
    command: "-H unix:///var/run/docker.sock"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
